version: '3'

services:
  authdb:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5454:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: application
      POSTGRES_PASSWORD: application
  applicationdb:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5455:5432
    volumes:
      - ./app_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: application
      POSTGRES_PASSWORD: application
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:16.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: authdb
      DB_DATABASE: application
      DB_USER: application
      DB_SCHEMA: public
      DB_PASSWORD: application
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8091:8080
    depends_on:
      - authdb
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=application